/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import database.dbConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhanuka
 */
public class expireProducts extends javax.swing.JPanel {

    /**
     * Creates new form expireProducts
     */
    public expireProducts() {
        initComponents();
        expireTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expire_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(234, 234, 254));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Products Close to Expire");
        add(jLabel1);
        jLabel1.setBounds(230, 20, 210, 30);

        expire_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "barcode", "product_ID", "Name", "Expire Date", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(expire_table);
        if (expire_table.getColumnModel().getColumnCount() > 0) {
            expire_table.getColumnModel().getColumn(0).setPreferredWidth(30);
            expire_table.getColumnModel().getColumn(1).setMinWidth(30);
            expire_table.getColumnModel().getColumn(1).setPreferredWidth(30);
            expire_table.getColumnModel().getColumn(2).setPreferredWidth(100);
            expire_table.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 600, 230);
    }// </editor-fold>//GEN-END:initComponents
 public void expireTable(){
        DefaultTableModel table = (DefaultTableModel) expire_table.getModel();
        table.setRowCount(0);
        
        try {
            
             DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
             Date date = new Date();
             String current_date= dateFormat.format(date);
            
            Statement con = dbConnection.db().createStatement();
            ResultSet record =  con.executeQuery("SELECT * \n" +
                                          "FROM supplied_products \n" +
                                          "WHERE expire_date >=  '"+current_date+"' \n" +
                                          "AND expire_date <= DATE_ADD(  '"+current_date+"', INTERVAL 7 DAY ) " );
             
            while(record.next()){
               
               Statement con2 = dbConnection.db().createStatement();
               ResultSet record2 =  con2.executeQuery("SELECT stock.bar_code, stock.product_id, stock.qauntity, products.product_name, supplied_products.expire_date\n" +
                                                      "FROM stock\n" +
                                                      "INNER JOIN products ON products.product_id = stock.product_id\n" +
                                                      "INNER JOIN supplied_products ON supplied_products.bar_code = stock.bar_code\n" +
                                                      "WHERE stock.bar_code ='"+record.getString("bar_code")+"'" );                           
                
                
                while(record2.next()){
                    
                Vector rc = new Vector();
                rc.add(record2.getString("stock.bar_code"));
                rc.add(record2.getString("stock.product_id"));
                rc.add(record2.getString("products.product_name"));
                rc.add(record2.getString("supplied_products.expire_date"));
                rc.add(record2.getString("stock.qauntity"));
                table.addRow(rc);
                
                 }      }                 
                                
        } catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable expire_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
