/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import database.dbConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Dhanuka
 */
public class notificationMain extends javax.swing.JPanel {

    /**
     * Creates new form NotificationMain
     */
    public notificationMain() {
        initComponents();
        notifyTabelUpdate(); 
        
       //buttonNotify();
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordersbtn = new javax.swing.JButton();
        expirebtn = new javax.swing.JButton();
        lowStockbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        notify_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        not_message = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(234, 234, 254));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        ordersbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ordersbtn.setForeground(new java.awt.Color(0, 0, 153));
        ordersbtn.setText("ORDERS");
        ordersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersbtnActionPerformed(evt);
            }
        });
        add(ordersbtn);
        ordersbtn.setBounds(590, 10, 100, 35);

        expirebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        expirebtn.setForeground(new java.awt.Color(0, 0, 153));
        expirebtn.setText("EXPIRING PRODUCT");
        expirebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expirebtnActionPerformed(evt);
            }
        });
        add(expirebtn);
        expirebtn.setBounds(440, 10, 150, 35);

        lowStockbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lowStockbtn.setForeground(new java.awt.Color(0, 0, 153));
        lowStockbtn.setText("LOW STOCK");
        lowStockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStockbtnActionPerformed(evt);
            }
        });
        add(lowStockbtn);
        lowStockbtn.setBounds(340, 10, 100, 35);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Notification History");
        add(jLabel1);
        jLabel1.setBounds(40, 10, 220, 40);

        notify_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Date Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notify_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notify_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(notify_table);
        if (notify_table.getColumnModel().getColumnCount() > 0) {
            notify_table.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 40, 452, 160);

        jLabel2.setText("Message");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(100, 230, 70, 14);

        not_message.setColumns(20);
        not_message.setRows(5);
        jScrollPane2.setViewportView(not_message);

        jLayeredPane1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 260, 450, 100);

        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(570, 110, 80, 30);

        add(jLayeredPane1);
        jLayeredPane1.setBounds(10, 70, 680, 420);
        add(jSeparator1);
        jSeparator1.setBounds(10, 60, 680, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void lowStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStockbtnActionPerformed
       
       bcolreset(lowStockbtn);
       lowStock a = new lowStock();
       jLayeredPane1.removeAll();
       a.setSize(680, 420);
       a.setVisible(true);
       jLayeredPane1.add(a);
       jLayeredPane1.moveToFront(a);
       
      
    }//GEN-LAST:event_lowStockbtnActionPerformed

    private void notify_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notify_tableMouseClicked
        try{
         Statement con = dbConnection.db().createStatement();
         ResultSet record =  con.executeQuery("SELECT not_message FROM notification WHERE not_id='"+notify_table.getValueAt(notify_table.getSelectedRow(), 0)+"'" );
            while(record.next()){
            not_message.setText(record.getString("not_message"));
            }
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_notify_tableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
         Statement con = dbConnection.db().createStatement();
         con.executeUpdate("DELETE FROM notification" );
         
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        notifyTabelUpdate();
        not_message.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void expirebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expirebtnActionPerformed

       expireProducts a = new expireProducts();
       jLayeredPane1.removeAll();
       a.setSize(680, 420);
       a.setVisible(true);
       jLayeredPane1.add(a);
       jLayeredPane1.moveToFront(a);
    }//GEN-LAST:event_expirebtnActionPerformed

    private void ordersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersbtnActionPerformed
       order a = new order();
       jLayeredPane1.removeAll();
       a.setSize(680, 420);
       a.setVisible(true);
       jLayeredPane1.add(a);
       jLayeredPane1.moveToFront(a);
    }//GEN-LAST:event_ordersbtnActionPerformed

    
      public void notifyTabelUpdate() {
        DefaultTableModel table = (DefaultTableModel) notify_table.getModel();
        table.setRowCount(0);
        
        try {
            Statement con = dbConnection.db().createStatement();
            java.sql.ResultSet record =  con.executeQuery("SELECT * FROM notification ORDER BY not_id DESC " );
            while(record.next()){
                Vector rc = new Vector();
                rc.add(record.getString("not_id"));
                rc.add(record.getString("not_type"));
                rc.add(record.getString("not_dateTime"));
               
                table.addRow(rc);
            }
        } catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
   
      //Change color to Red  
      /*
    public void buttonNotify(){
    
     try{
     Statement con = dbConnection.db().createStatement();
     
    //Expire Button  
   
    ResultSet record =  con.executeQuery("SELECT COUNT(*) AS total FROM supplied_products WHERE supplied_date >= '2014-10-30' AND expire_date <= '2014-11-07' " ); 
    while(record.next()){
    if(Integer.parseInt(record.getString("total"))>0){
        bcolred(expirebtn);
    }
     }
    
   
     
    //Low Stock button
    ResultSet record2 =  con.executeQuery("SELECT product_id FROM stock GROUP BY product_id HAVING SUM(qauntity) <= 10 " ); 
    int qty=0;
     while(record2.next()){
        qty++;
     }
    if(qty>0){
        bcolred(lowStockbtn);
    }
     
    
     }catch(Exception ex) {
       Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    */
    
    public void bcolred(JButton a) {
        a.setBackground(new java.awt.Color(204, 0, 0));
        a.setForeground(new java.awt.Color(255, 255, 255));
    }
     
     public void bcolreset(JButton a) {
        a.setBackground(new java.awt.Color(204,204,255));
        a.setForeground(new java.awt.Color(0, 0, 153));
    }
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton expirebtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JButton lowStockbtn;
    private javax.swing.JTextArea not_message;
    private javax.swing.JTable notify_table;
    private javax.swing.JButton ordersbtn;
    // End of variables declaration//GEN-END:variables
} 

