/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.dbConnection;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka
 */
public class reports extends javax.swing.JPanel {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        report_grnBtngrp_amt = new javax.swing.ButtonGroup();
        report_grnBtngrp_qty = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        report_grn = new javax.swing.JButton();
        report_trans = new javax.swing.JButton();
        report_btn_orders = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        grn_txt_year = new javax.swing.JComboBox();
        grn_txt_month = new javax.swing.JComboBox();
        grn_txt_dates = new javax.swing.JComboBox();
        grn_txt_ex_date = new javax.swing.JComboBox();
        grn_txt_ex_month = new javax.swing.JComboBox();
        grn_txt_ex_year = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radio_qty_eql = new javax.swing.JRadioButton();
        radio_qty_lager = new javax.swing.JRadioButton();
        radio_qty_less = new javax.swing.JRadioButton();
        report_txt_supID = new javax.swing.JTextField();
        report_txt_proID = new javax.swing.JTextField();
        report_txt_qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radio_amt_eql = new javax.swing.JRadioButton();
        radio_amt_lager = new javax.swing.JRadioButton();
        radio_amt_less = new javax.swing.JRadioButton();
        report_txt_amt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        report_chk_deli = new javax.swing.JCheckBox();
        report_chk_cancel = new javax.swing.JCheckBox();
        report_chk_notYet = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        report_txt_cusID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radio_Transamt_eql = new javax.swing.JRadioButton();
        radio_Transamt_lager = new javax.swing.JRadioButton();
        radio_Transamt_less = new javax.swing.JRadioButton();
        report_txt_transamt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(234, 234, 254));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Reports");
        add(jLabel1);
        jLabel1.setBounds(320, 10, 90, 30);

        report_grn.setText("GRN");
        report_grn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_grnActionPerformed(evt);
            }
        });
        add(report_grn);
        report_grn.setBounds(70, 410, 100, 40);

        report_trans.setText("Transactions");
        report_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_transActionPerformed(evt);
            }
        });
        add(report_trans);
        report_trans.setBounds(310, 410, 100, 40);

        report_btn_orders.setText("Orders");
        report_btn_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_btn_ordersActionPerformed(evt);
            }
        });
        add(report_btn_orders);
        report_btn_orders.setBounds(560, 410, 100, 40);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1);
        jSeparator1.setBounds(230, 100, 10, 360);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(470, 90, 10, 360);

        grn_txt_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", " " }));
        grn_txt_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grn_txt_yearActionPerformed(evt);
            }
        });
        add(grn_txt_year);
        grn_txt_year.setBounds(80, 50, 80, 20);

        grn_txt_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        add(grn_txt_month);
        grn_txt_month.setBounds(170, 50, 60, 20);

        grn_txt_dates.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        add(grn_txt_dates);
        grn_txt_dates.setBounds(240, 50, 60, 20);

        grn_txt_ex_date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        grn_txt_ex_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grn_txt_ex_dateActionPerformed(evt);
            }
        });
        add(grn_txt_ex_date);
        grn_txt_ex_date.setBounds(610, 50, 60, 20);

        grn_txt_ex_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        add(grn_txt_ex_month);
        grn_txt_ex_month.setBounds(540, 50, 60, 20);

        grn_txt_ex_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        add(grn_txt_ex_year);
        grn_txt_ex_year.setBounds(450, 50, 80, 20);

        jLabel2.setText("From :");
        add(jLabel2);
        jLabel2.setBounds(20, 55, 40, 14);

        jLabel3.setText("To :");
        add(jLabel3);
        jLabel3.setBounds(410, 55, 34, 14);

        jLabel4.setText("Sup ID :");
        add(jLabel4);
        jLabel4.setBounds(20, 120, 50, 14);

        jLabel5.setText("Product ID :");
        add(jLabel5);
        jLabel5.setBounds(20, 160, 70, 14);

        jLabel6.setText("Quantity :");
        add(jLabel6);
        jLabel6.setBounds(20, 310, 60, 14);

        report_grnBtngrp_qty.add(radio_qty_eql);
        radio_qty_eql.setText("=");
        add(radio_qty_eql);
        radio_qty_eql.setBounds(70, 305, 40, 23);

        report_grnBtngrp_qty.add(radio_qty_lager);
        radio_qty_lager.setText(">");
        add(radio_qty_lager);
        radio_qty_lager.setBounds(70, 330, 40, 23);

        report_grnBtngrp_qty.add(radio_qty_less);
        radio_qty_less.setText("<");
        add(radio_qty_less);
        radio_qty_less.setBounds(70, 355, 40, 23);
        add(report_txt_supID);
        report_txt_supID.setBounds(120, 110, 50, 30);
        add(report_txt_proID);
        report_txt_proID.setBounds(120, 150, 50, 30);
        add(report_txt_qty);
        report_txt_qty.setBounds(120, 300, 90, 30);

        jLabel7.setText("Amount :");
        add(jLabel7);
        jLabel7.setBounds(20, 220, 50, 14);

        report_grnBtngrp_amt.add(radio_amt_eql);
        radio_amt_eql.setText("=");
        add(radio_amt_eql);
        radio_amt_eql.setBounds(70, 215, 40, 23);

        report_grnBtngrp_amt.add(radio_amt_lager);
        radio_amt_lager.setText(">");
        add(radio_amt_lager);
        radio_amt_lager.setBounds(70, 240, 40, 23);

        report_grnBtngrp_amt.add(radio_amt_less);
        radio_amt_less.setText("<");
        add(radio_amt_less);
        radio_amt_less.setBounds(70, 265, 40, 23);
        add(report_txt_amt);
        report_txt_amt.setBounds(120, 210, 90, 30);

        jLabel8.setText("Status :");
        add(jLabel8);
        jLabel8.setBounds(490, 220, 50, 14);

        report_chk_deli.setText("Delivered");
        add(report_chk_deli);
        report_chk_deli.setBounds(550, 210, 80, 23);

        report_chk_cancel.setText("Cancelled");
        report_chk_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_chk_cancelActionPerformed(evt);
            }
        });
        add(report_chk_cancel);
        report_chk_cancel.setBounds(550, 240, 80, 23);

        report_chk_notYet.setText("Not deliver yet");
        add(report_chk_notYet);
        report_chk_notYet.setBounds(550, 270, 110, 23);

        jLabel9.setText("Cus ID :");
        add(jLabel9);
        jLabel9.setBounds(490, 120, 50, 14);
        add(report_txt_cusID);
        report_txt_cusID.setBounds(560, 110, 50, 30);

        jLabel10.setText("Amount :");
        add(jLabel10);
        jLabel10.setBounds(250, 220, 50, 14);

        buttonGroup1.add(radio_Transamt_eql);
        radio_Transamt_eql.setText("=");
        radio_Transamt_eql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Transamt_eqlActionPerformed(evt);
            }
        });
        add(radio_Transamt_eql);
        radio_Transamt_eql.setBounds(300, 220, 40, 23);

        buttonGroup1.add(radio_Transamt_lager);
        radio_Transamt_lager.setText(">");
        add(radio_Transamt_lager);
        radio_Transamt_lager.setBounds(300, 250, 40, 23);

        buttonGroup1.add(radio_Transamt_less);
        radio_Transamt_less.setText("<");
        radio_Transamt_less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_Transamt_lessActionPerformed(evt);
            }
        });
        add(radio_Transamt_less);
        radio_Transamt_less.setBounds(300, 280, 40, 23);
        add(report_txt_transamt);
        report_txt_transamt.setBounds(350, 220, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void report_grnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_grnActionPerformed
        
        
        String sql_cmd="";
        String showRcrdMsg="";
        //there should be 16 main If
        //1
        if(report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){
            //showRcrdMsg="Showing all Records";
            sql_cmd="SELECT * FROM supplied_products WHERE \n"
                    +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
        //2    
        }else if (!report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){
             
             ////showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+"";
             
             sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND \n"
                    +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";

        //3
        }else if (!report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){
            
            //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nProduct ID="+report_txt_proID.getText()+"";
            
            sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND\n"
                   +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";

        //4
        }else if (!report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){
        
            //radio button Amount
            if(radio_amt_eql.isSelected()){
                //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nTotal Amount = "+report_txt_amt.getText()+"";

                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND \n"
                       +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";

            
            }else if(radio_amt_lager.isSelected()){
                //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nTotal Amount > "+report_txt_amt.getText()+"";

                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";

            
            }else if(radio_amt_less.isSelected()){
                //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nTotal Amount < "+report_txt_amt.getText()+"";

                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
        //5    
        }else if (!report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
            
             //radio button Qty
            if(radio_qty_eql.isSelected()){
               // showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nQuantity = "+report_txt_qty.getText()+"";

                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_qty_lager.isSelected()){
                //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nQuantity > "+report_txt_qty.getText()+"";
    
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_qty_less.isSelected()){
                //showRcrdMsg="Showing all Records \nsupplier ID = "+report_txt_supID.getText()+" \nQuantity < "+report_txt_qty.getText()+"";

                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
        
        //6
        }else if (report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){

          sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND \n"
                  +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
           
        //7
        }else if (report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){

              //radio button Amount
            if(radio_amt_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
        //8   
        }else if (report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
             //radio button Qty
            if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
        //9    
        }else if (report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){

            //radio button Amount
            if(radio_amt_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount ='"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount >'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount <'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
        //10   
        }else if (report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){

        
             //BOTH radio button 
            if(radio_amt_eql.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_amt_lager.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            
            }else if(radio_amt_less.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
        //11
        }else if (report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){

             //radio button Qty
            if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
           
            else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
        //12    
        }else if (report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
            
             //BOTH radio button 
            if(radio_amt_eql.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_amt_lager.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"'AND \n "
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            
            }else if(radio_amt_less.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE product_id ='"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
        
        //13
        }else if (!report_txt_supID.getText().equals("") && report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
            //BOTH radio button 
            if(radio_amt_eql.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_amt_lager.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            
            }else if(radio_amt_less.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
        
        //14
         }else if (!report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
   
               //radio button Qty
            if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
          //15
         }else if (!report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && report_txt_qty.getText().equals("")){
              //radio button Amount
            if(radio_amt_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            else if(radio_amt_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
           
        //16   
        }else if (!report_txt_supID.getText().equals("") && !report_txt_proID.getText().equals("")  && !report_txt_amt.getText().equals("") && !report_txt_qty.getText().equals("")){
            //BOTH radio button 
            if(radio_amt_eql.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount ='"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            }else if(radio_amt_lager.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount >'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
            
            }else if(radio_amt_less.isSelected()){
                if(radio_qty_eql.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity ='"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_lager.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity >'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            
                else if(radio_qty_less.isSelected())
                sql_cmd="SELECT * FROM supplied_products WHERE supplier_id = '"+report_txt_supID.getText()+"' AND product_id = '"+report_txt_proID.getText()+"' AND supplied_total_amount <'"+report_txt_amt.getText()+"' AND supplied_qauntity <'"+report_txt_qty.getText()+"' AND \n"
                        +"supplied_date >='"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' AND supplied_date <='"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' ";
            }
            
            
        }  
            
            
         Document doc = new Document();
        
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                            Date date = new Date();
                            String report_date = dateFormat.format(date);
                            
                            
                            
        try{
        PdfWriter.getInstance(doc, new FileOutputStream("report_grn.pdf"));
        doc.open();
       
        Statement con = dbConnection.db().createStatement();
        ResultSet record =  con.executeQuery(sql_cmd);
        //ResultSet record2 =  con.executeQuery("SELECT COUNT(*) AS total FROM supplied_products ");
        
        
        
        Paragraph H1 = new Paragraph("Rajaguru Stores" , FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE));
            H1.setAlignment(Element.ALIGN_CENTER);
            H1.setSpacingAfter(20);
        doc.add(H1);
        
        
        Paragraph H2 = new Paragraph("Good Recieve Note(GRN)" , FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
        doc.add(H2);
        
        Paragraph H3 = new Paragraph("Date Created : "+report_date+"" , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        doc.add(H3);
        
        Paragraph H4 = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
        H4.setSpacingAfter(20);
        doc.add(H4);
        
        Paragraph H6 = new Paragraph("Showing Records Between Supplied Date '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"'"
                                    +" & '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' " , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        H6.setSpacingAfter(20);
        doc.add(H6);
        
        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(90);
        
        PdfPCell cell1 = new    PdfPCell(new Paragraph("Barcode"));
        cell1.setBackgroundColor(BaseColor.GRAY);
       
        
        PdfPCell cell2 = new    PdfPCell(new Paragraph("Product ID"));
        cell2.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell3 = new    PdfPCell(new Paragraph("Supplier ID"));
        cell3.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell4 = new    PdfPCell(new Paragraph("Quantity"));
        cell4.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell5 = new    PdfPCell(new Paragraph("Supplied Date"));
        cell5.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell6 = new    PdfPCell(new Paragraph("Expire Date"));
        cell6.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell7 = new    PdfPCell(new Paragraph("Amount"));
        cell7.setBackgroundColor(BaseColor.GRAY);
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cell4);
            table.addCell(cell5);
            table.addCell(cell6);
            table.addCell(cell7);
        
        
            while(record.next()){
            table.addCell(""+record.getString("bar_code")+"");
            table.addCell(""+record.getString("product_id")+"");
            table.addCell(""+record.getString("supplier_id")+"");
            table.addCell(""+record.getString("supplied_qauntity")+"");
            table.addCell(""+record.getString("supplied_date")+"");
            table.addCell(""+record.getString("expire_date")+"");
            table.addCell(""+record.getString("supplied_total_amount")+"");
                    }           
         doc.add(table);   
         
        //Paragraph H5 = new Paragraph("Total Records : "+record2.getString("total")+"");
        //doc.add(H5); 
         
        doc.close();
        openReportGrn();
        }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"There is something wrong of inputs Or \nClose the currently open PDF report and Try Again....! ");
           Logger.getLogger(grnWindow.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
    }//GEN-LAST:event_report_grnActionPerformed

    private void report_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_transActionPerformed
       
         String sql_cmd="";
        String showRcrdMsg="";
        //there should be 16 main If
        //1
        if(report_txt_transamt.getText().equals("") ){
            showRcrdMsg="Showing all Records";
            sql_cmd="SELECT * FROM transactions WHERE dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' "
                    + "AND dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
            
            
        //2    
        }
        
        else{
        
              if(radio_Transamt_eql.isSelected())
                sql_cmd="SELECT * FROM transactions WHERE total_price ='"+report_txt_transamt.getText()+"'AND \n"
                        + "dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
            
            else if(radio_Transamt_lager.isSelected())
                sql_cmd="SELECT * FROM transactions WHERE  total_price >'"+report_txt_transamt.getText()+"' AND \n"
                        + "dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
            
            else if(radio_Transamt_less.isSelected())
                sql_cmd="SELECT * FROM transactions WHERE total_price <'"+report_txt_transamt.getText()+"' AND \n"
                        + "dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
        //8   
           
        
        }
        
         Document doc = new Document();
        
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                            Date date = new Date();
                            String report_date = dateFormat.format(date);
                            
                            
                            
        try{
        PdfWriter.getInstance(doc, new FileOutputStream("report_transactions.pdf"));
        doc.open();
       
        Statement con = dbConnection.db().createStatement();
        
        ResultSet record =  con.executeQuery(sql_cmd);
           
        //ResultSet record2 =  con.executeQuery("SELECT COUNT(*) AS total FROM supplied_products ");
        
        
        
        Paragraph H1 = new Paragraph("Rajaguru Stores" , FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE));
            H1.setAlignment(Element.ALIGN_CENTER);
            H1.setSpacingAfter(20);
        doc.add(H1);
        
        
        Paragraph H2 = new Paragraph("Transactions" , FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
        doc.add(H2);
        
        Paragraph H3 = new Paragraph("Date Created : "+report_date+"" , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        doc.add(H3);
        
        Paragraph H4 = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
        H4.setSpacingAfter(20);
        doc.add(H4);
        
          Paragraph H6 = new Paragraph("Showing Records Between Transaction Date '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"'"
                                    +" & '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' " , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        H6.setSpacingAfter(20);
        doc.add(H6);
        
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(70);
        
        PdfPCell cell1 = new    PdfPCell(new Paragraph("Transaction ID"));
        cell1.setBackgroundColor(BaseColor.GRAY);
       
        
        PdfPCell cell2 = new    PdfPCell(new Paragraph("Date/Time"));
        cell2.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell3 = new    PdfPCell(new Paragraph("Total Price"));
        cell3.setBackgroundColor(BaseColor.GRAY);
        
       
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
           
        
        
            while(record.next()){
            table.addCell(""+record.getString("transaction_id")+"");
            table.addCell(""+record.getString("dateTime")+"");
            table.addCell(""+record.getString("total_price")+"");
           
                    }           
         doc.add(table);   
         
        //Paragraph H5 = new Paragraph("Total Records : "+record2.getString("total")+"");
        //doc.add(H5); 
         
        doc.close();
        openReportTrans();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"There is something wrong of inputs Or \nClose the currently open PDF report and Try Again....! ");
           Logger.getLogger(grnWindow.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
        
        
    }//GEN-LAST:event_report_transActionPerformed

    private void grn_txt_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grn_txt_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grn_txt_yearActionPerformed

    private void grn_txt_ex_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grn_txt_ex_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grn_txt_ex_dateActionPerformed

    private void report_chk_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_chk_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_report_chk_cancelActionPerformed

    private void report_btn_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_btn_ordersActionPerformed
        String sql_cmd="";
        //there shoul be 16 if
        //1
        if(report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
        
            sql_cmd="SELECT * FROM order_details WHERE order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' "
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'"; 
            
        //2
        }else if(!report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"'AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
            
        //3    
        }else if(!report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND order_status='Delivered' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
            
        //4  
        }else if(!report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND order_status='Cancelled' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

        //5  
        }else if(!report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND order_status='' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

        //6  
        }else if(report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE order_status='Delivered' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

        //7  
        }else if(report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE (order_status='Delivered' OR order_status='Cancelled') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
        
        //8 recorrected
        }else if(report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE (order_status='Delivered' OR order_status='') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

        //9
        }else if(report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE order_status='Cancelled' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

         //10
        }else if(report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE (order_status='Cancelled' OR order_status='') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

         //11
        }else if(report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE order_status='' AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

         //12
        }else if(report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'"; 

         //13
        }else if(!report_txt_cusID.getText().equals("") && !report_chk_deli.isSelected() && report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND (order_status='Cancelled' OR order_status='') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00' ";
        
        //14    
        }else if(!report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && !report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND (order_status='Delivered' OR order_status='') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

         //15    
        }else if(!report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && report_chk_cancel.isSelected() && !report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"' AND (order_status='Delivered' OR order_status='Cancelled') AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";
        
        //16
        }else if(!report_txt_cusID.getText().equals("") && report_chk_deli.isSelected() && report_chk_cancel.isSelected() && report_chk_notYet.isSelected()){
            
            sql_cmd="SELECT * FROM order_details WHERE cus_id='"+report_txt_cusID.getText()+"'AND \n"
                        + "order_dateTime >= '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_dates.getSelectedItem()+" "+"00:00:00' \n"
                    + "AND order_dateTime <= '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+" " +"00:00:00'";

        }

          Document doc = new Document();
        
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                            Date date = new Date();
                            String report_date = dateFormat.format(date);
                            
                            
                            
        try{
        PdfWriter.getInstance(doc, new FileOutputStream("report_orders.pdf"));
        doc.open();
       
        Statement con = dbConnection.db().createStatement();
        ResultSet record =  con.executeQuery(sql_cmd);
        //ResultSet record2 =  con.executeQuery("SELECT COUNT(*) AS total FROM supplied_products ");
        
        
        
        Paragraph H1 = new Paragraph("Rajaguru Stores" , FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE));
            H1.setAlignment(Element.ALIGN_CENTER);
            H1.setSpacingAfter(20);
        doc.add(H1);
        
        
        Paragraph H2 = new Paragraph("Order Details" , FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
        doc.add(H2);
        
        Paragraph H3 = new Paragraph("Date Created : "+report_date+"" , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        doc.add(H3);
        
        Paragraph H4 = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
        H4.setSpacingAfter(20);
        doc.add(H4);
        
       Paragraph H6 = new Paragraph("Showing Records Between Ordered Date '"+grn_txt_year.getSelectedItem()+"-"+grn_txt_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"'"
                                    +" & '"+grn_txt_ex_year.getSelectedItem()+"-"+grn_txt_ex_month.getSelectedItem()+"-"+grn_txt_ex_date.getSelectedItem()+"' " , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        H6.setSpacingAfter(20);
        doc.add(H6);
        
        PdfPTable table = new PdfPTable(11);
        table.setWidthPercentage(95);
        
        PdfPCell cell1 = new    PdfPCell(new Paragraph("Order ID"));
        cell1.setBackgroundColor(BaseColor.GRAY);
       
        
        PdfPCell cell2 = new    PdfPCell(new Paragraph("Customer ID"));
        cell2.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell3 = new    PdfPCell(new Paragraph("Customer Name"));
        cell3.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell4 = new    PdfPCell(new Paragraph("Address"));
        cell4.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell5 = new    PdfPCell(new Paragraph("Phone No"));
        cell5.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell6 = new    PdfPCell(new Paragraph("Ordered Date"));
        cell6.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell7 = new    PdfPCell(new Paragraph("Delivery Date"));
        cell7.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell8 = new    PdfPCell(new Paragraph("Delivery Time"));
        cell8.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell9 = new    PdfPCell(new Paragraph("Anytime"));
        cell9.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell10 = new    PdfPCell(new Paragraph("Message"));
        cell10.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell11 = new    PdfPCell(new Paragraph("Status"));
        cell11.setBackgroundColor(BaseColor.GRAY);
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cell4);
            table.addCell(cell5);
            table.addCell(cell6);
            table.addCell(cell7);
            table.addCell(cell8);
            table.addCell(cell9);
            table.addCell(cell10);
            table.addCell(cell11);
        
        
            while(record.next()){
            table.addCell(""+record.getString("order_id")+"");
            table.addCell(""+record.getString("cus_id")+"");
            table.addCell(""+record.getString("order_cus_name")+"");
            table.addCell(""+record.getString("order_cus_address")+"");
            table.addCell(""+record.getString("order_cus_phone")+"");
            table.addCell(""+record.getString("order_dateTime")+"");
            table.addCell(""+record.getString("order_delivery_date")+"");
            table.addCell(""+record.getString("order_delivery_time")+"");
            table.addCell(""+record.getString("delivery_anytime")+"");
            table.addCell(""+record.getString("order_other_messages")+"");
            table.addCell(""+record.getString("order_status")+"");
                    }           
         doc.add(table);   
         
        //Paragraph H5 = new Paragraph("Total Records : "+record2.getString("total")+"");
        //doc.add(H5); 
         
        doc.close();
        openReportOrders();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"There is something wrong of inputs Or \nClose the currently open PDF report and Try Again....! ");
           Logger.getLogger(grnWindow.class.getName()).log(Level.SEVERE, null, ex);

        }
        
    }//GEN-LAST:event_report_btn_ordersActionPerformed

    private void radio_Transamt_eqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Transamt_eqlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_Transamt_eqlActionPerformed

    private void radio_Transamt_lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_Transamt_lessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_Transamt_lessActionPerformed

    public void openReportGrn(){
        
        try {
            Desktop.getDesktop().open(new File("report_grn.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void openReportTrans(){
         try {
            Desktop.getDesktop().open(new File("report_transactions.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
      
     }
     public void openReportOrders(){
        try {
            Desktop.getDesktop().open(new File("report_orders.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        try{
        
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Dhanuka\\Documents\\NetBeansProjects\\rajaguru_stores_3\\report_orders.pdf");
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Sorry Can't Open the Report now...!");
        
        }    
        */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox grn_txt_dates;
    private javax.swing.JComboBox grn_txt_ex_date;
    private javax.swing.JComboBox grn_txt_ex_month;
    private javax.swing.JComboBox grn_txt_ex_year;
    private javax.swing.JComboBox grn_txt_month;
    private javax.swing.JComboBox grn_txt_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radio_Transamt_eql;
    private javax.swing.JRadioButton radio_Transamt_lager;
    private javax.swing.JRadioButton radio_Transamt_less;
    private javax.swing.JRadioButton radio_amt_eql;
    private javax.swing.JRadioButton radio_amt_lager;
    private javax.swing.JRadioButton radio_amt_less;
    private javax.swing.JRadioButton radio_qty_eql;
    private javax.swing.JRadioButton radio_qty_lager;
    private javax.swing.JRadioButton radio_qty_less;
    private javax.swing.JButton report_btn_orders;
    private javax.swing.JCheckBox report_chk_cancel;
    private javax.swing.JCheckBox report_chk_deli;
    private javax.swing.JCheckBox report_chk_notYet;
    private javax.swing.JButton report_grn;
    private javax.swing.ButtonGroup report_grnBtngrp_amt;
    private javax.swing.ButtonGroup report_grnBtngrp_qty;
    private javax.swing.JButton report_trans;
    private javax.swing.JTextField report_txt_amt;
    private javax.swing.JTextField report_txt_cusID;
    private javax.swing.JTextField report_txt_proID;
    private javax.swing.JTextField report_txt_qty;
    private javax.swing.JTextField report_txt_supID;
    private javax.swing.JTextField report_txt_transamt;
    // End of variables declaration//GEN-END:variables
}
