/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import database.dbConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhanuka
 */
public class customerDetails extends javax.swing.JFrame {

    /**
     * Creates new form customerDetails
     */
    public customerDetails() {
        initComponents();
        cusTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cus_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cus_address = new javax.swing.JTextField();
        cus_name = new javax.swing.JLabel();
        cus_email = new javax.swing.JLabel();
        cus_phoneNo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cusIdsrch = new javax.swing.JTextField();

        setTitle("Customer Details");
        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        cus_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cus_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cus_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cus_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 110, 230, 250);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Online Customer's Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 300, 40);

        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 50, 14);

        jLabel4.setText("Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 60, 14);

        jLabel5.setText("Phone No :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 70, 14);

        jLabel6.setText("E-mail :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 300, 50, 14);
        getContentPane().add(cus_address);
        cus_address.setBounds(120, 180, 210, 30);
        getContentPane().add(cus_name);
        cus_name.setBounds(120, 120, 200, 25);
        getContentPane().add(cus_email);
        cus_email.setBounds(120, 290, 210, 25);
        getContentPane().add(cus_phoneNo);
        cus_phoneNo.setBounds(120, 240, 210, 25);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 240, 210, 25);

        jLabel2.setText("Search Customer ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 80, 120, 14);

        cusIdsrch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cusIdsrchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cusIdsrchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusIdsrchKeyTyped(evt);
            }
        });
        getContentPane().add(cusIdsrch);
        cusIdsrch.setBounds(460, 70, 90, 30);

        setSize(new java.awt.Dimension(616, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusIdsrchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusIdsrchKeyReleased
        
           try {

                DefaultTableModel dtm = (DefaultTableModel) cus_table.getModel();
                dtm.setRowCount(0);
                if (!(cusIdsrch.getText().equals(""))) {
                    Statement con = dbConnection.db().createStatement();
                    ResultSet rs1 = con.executeQuery("SELECT * FROM customer_details WHERE cus_id LIKE'" + cusIdsrch.getText() + "%'");
                    while (rs1.next()) {
                        Vector v1 = new Vector();
                        v1.add(rs1.getString("cus_id"));
                        v1.add(rs1.getString("cus_name"));
                        dtm.addRow(v1);
                    }
                } else {
                    cusTable();
                }
            } catch (Exception ex) {
                Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
    }//GEN-LAST:event_cusIdsrchKeyReleased

    private void cus_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cus_tableMouseClicked
           try{
         Statement con = dbConnection.db().createStatement();
         ResultSet record =  con.executeQuery("SELECT * FROM customer_details WHERE cus_id='"+cus_table.getValueAt(cus_table.getSelectedRow(), 0)+"'" );
            while(record.next()){
            cus_name.setText(record.getString("cus_name"));
            cus_address.setText(record.getString("cus_address"));
            cus_phoneNo.setText(record.getString("cus_phone_no"));
            cus_email.setText(record.getString("cus_email"));
            }
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cus_tableMouseClicked

    private void cusIdsrchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusIdsrchKeyTyped
        
    }//GEN-LAST:event_cusIdsrchKeyTyped

    private void cusIdsrchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusIdsrchKeyPressed

        cusTable();
    }//GEN-LAST:event_cusIdsrchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerDetails().setVisible(true);
            }
        });
    }

      public void cusTable() {
        DefaultTableModel table = (DefaultTableModel) cus_table.getModel();
        table.setRowCount(0);
        
        try {
            Statement con = dbConnection.db().createStatement();
            java.sql.ResultSet record =  con.executeQuery("SELECT * FROM customer_details" );
            while(record.next()){
                Vector rc = new Vector();
                rc.add(record.getString("cus_id"));
                rc.add(record.getString("cus_name"));
                table.addRow(rc);
            }
        } catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cusIdsrch;
    private javax.swing.JTextField cus_address;
    private javax.swing.JLabel cus_email;
    private javax.swing.JLabel cus_name;
    private javax.swing.JLabel cus_phoneNo;
    private javax.swing.JTable cus_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
