/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import database.dbConnection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhanuka
 */
public class lowStock extends javax.swing.JPanel {

    /**
     * Creates new form lowStock
     */
    public lowStock() {
        initComponents();
        productsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowstock_tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        not_lbl_supName = new javax.swing.JLabel();
        not_lbl_phoneNo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 234, 254));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Low Stock Product");
        add(jLabel1);
        jLabel1.setBounds(260, 20, 150, 17);

        lowstock_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Product_ID", "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lowstock_tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lowstock_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowstock_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lowstock_tbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 90, 510, 220);

        jLabel2.setText("These Products are currently having low quntity in the store");
        add(jLabel2);
        jLabel2.setBounds(60, 60, 340, 14);

        jLabel3.setText("Last Supplier Name   -");
        add(jLabel3);
        jLabel3.setBounds(60, 330, 130, 14);

        jLabel4.setText("Contact No               -");
        add(jLabel4);
        jLabel4.setBounds(60, 360, 110, 14);
        add(not_lbl_supName);
        not_lbl_supName.setBounds(200, 325, 180, 20);
        add(not_lbl_phoneNo);
        not_lbl_phoneNo.setBounds(200, 355, 180, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void lowstock_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowstock_tblMouseClicked
              try{
         Statement con = dbConnection.db().createStatement();
         ResultSet record =  con.executeQuery("SELECT supplier_id FROM supplied_products WHERE bar_code='"+lowstock_tbl.getValueAt(lowstock_tbl.getSelectedRow(), 0)+"'" );
            while(record.next()){
                
                ResultSet record2 =  con.executeQuery("SELECT * FROM supplier_details WHERE supplier_id='"+record.getString("supplier_id")+"'" );
                         while(record2.next()){
                         
                             not_lbl_supName.setText(record2.getString("supplier_name"));
                             not_lbl_phoneNo.setText(record2.getString("supplier_phone"));
                       
                         }
            
            }
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_lowstock_tblMouseClicked

      public void productsTable(){
        DefaultTableModel table = (DefaultTableModel) lowstock_tbl.getModel();
        table.setRowCount(0);
        
        try {
            Statement con = dbConnection.db().createStatement();
            ResultSet record =  con.executeQuery("SELECT product_id FROM stock GROUP BY product_id HAVING SUM(qauntity) <= 10" );
             
            while(record.next()){
               
               Statement con2 = dbConnection.db().createStatement();
               ResultSet record2 =  con2.executeQuery("SELECT stock.bar_code,stock.product_id,stock.qauntity,products.product_name FROM stock INNER JOIN products ON products.product_id = stock.product_id WHERE stock.product_id = '"+record.getString("product_id")+"'" );                           
                
                
                while(record2.next()){
                    
                Vector rc = new Vector();
                rc.add(record2.getString("stock.bar_code"));
                rc.add(record2.getString("stock.product_id"));
                rc.add(record2.getString("products.product_name"));
                rc.add(record2.getString("stock.qauntity"));
                table.addRow(rc);
                
                 }      }                 
                                
        } catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lowstock_tbl;
    private javax.swing.JLabel not_lbl_phoneNo;
    private javax.swing.JLabel not_lbl_supName;
    // End of variables declaration//GEN-END:variables
}
