/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import database.dbConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhanuka
 */
public class order extends javax.swing.JPanel {

    /**
     * Creates new form order
     */
    public order() {
        initComponents();
        OrdersTableUpdate();
        notify_delvrd.setVisible(false);
        notify_notDel.setVisible(false);
        notify_cancelled.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_tbl_orders = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        order_tbl_qty = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        order_btn_delivery = new javax.swing.JButton();
        order_btn_cancel = new javax.swing.JButton();
        order_lbl_cusName = new javax.swing.JLabel();
        order_lbl_cusId = new javax.swing.JLabel();
        order_lbl_phoneNo = new javax.swing.JLabel();
        order_lbl_DilDate = new javax.swing.JLabel();
        order_lbl_DilTime = new javax.swing.JLabel();
        order_lbl_anytime = new javax.swing.JLabel();
        order_lbl_address = new javax.swing.JTextField();
        order_lbl_msg = new javax.swing.JTextField();
        notify_notDel = new javax.swing.JLabel();
        notify_delvrd = new javax.swing.JLabel();
        notify_cancelled = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 234, 254));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Orders");
        add(jLabel1);
        jLabel1.setBounds(300, 10, 80, 17);

        order_tbl_orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        order_tbl_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                order_tbl_ordersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(order_tbl_orders);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 290, 320);

        jLabel2.setText("Customer Name :");
        add(jLabel2);
        jLabel2.setBounds(320, 70, 100, 14);

        order_tbl_qty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product  ID", "Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(order_tbl_qty);

        add(jScrollPane2);
        jScrollPane2.setBounds(320, 160, 350, 110);

        jLabel3.setText("Cus ID :");
        add(jLabel3);
        jLabel3.setBounds(550, 40, 50, 14);

        jLabel4.setText("Address :");
        add(jLabel4);
        jLabel4.setBounds(320, 100, 60, 14);

        jLabel5.setText("Phone No :");
        add(jLabel5);
        jLabel5.setBounds(320, 130, 70, 14);

        jLabel6.setText("Delivery DateTime :");
        add(jLabel6);
        jLabel6.setBounds(320, 290, 110, 14);

        jLabel8.setText("Other Message :");
        add(jLabel8);
        jLabel8.setBounds(320, 330, 100, 14);

        order_btn_delivery.setText("Deliver");
        order_btn_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btn_deliveryActionPerformed(evt);
            }
        });
        add(order_btn_delivery);
        order_btn_delivery.setBounds(390, 370, 80, 30);

        order_btn_cancel.setText("Cancel");
        order_btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btn_cancelActionPerformed(evt);
            }
        });
        add(order_btn_cancel);
        order_btn_cancel.setBounds(510, 370, 80, 30);
        add(order_lbl_cusName);
        order_lbl_cusName.setBounds(430, 65, 230, 25);
        add(order_lbl_cusId);
        order_lbl_cusId.setBounds(610, 35, 50, 25);
        add(order_lbl_phoneNo);
        order_lbl_phoneNo.setBounds(430, 125, 150, 25);
        add(order_lbl_DilDate);
        order_lbl_DilDate.setBounds(440, 285, 70, 25);
        add(order_lbl_DilTime);
        order_lbl_DilTime.setBounds(520, 285, 140, 25);

        order_lbl_anytime.setForeground(new java.awt.Color(0, 51, 153));
        add(order_lbl_anytime);
        order_lbl_anytime.setBounds(620, 300, 50, 25);
        add(order_lbl_address);
        order_lbl_address.setBounds(430, 95, 230, 30);
        add(order_lbl_msg);
        order_lbl_msg.setBounds(440, 325, 220, 30);

        notify_notDel.setForeground(new java.awt.Color(204, 0, 0));
        notify_notDel.setText("Not   Deliver Yet");
        add(notify_notDel);
        notify_notDel.setBounds(20, 50, 100, 14);

        notify_delvrd.setForeground(new java.awt.Color(0, 51, 153));
        notify_delvrd.setText("Delivered");
        add(notify_delvrd);
        notify_delvrd.setBounds(20, 50, 100, 14);

        notify_cancelled.setForeground(new java.awt.Color(204, 0, 0));
        notify_cancelled.setText("Cancelled");
        add(notify_cancelled);
        notify_cancelled.setBounds(20, 50, 60, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customerRoll.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(480, 30, 35, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void order_tbl_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_tbl_ordersMouseClicked
         try{
         Statement con = dbConnection.db().createStatement();
         DefaultTableModel table = (DefaultTableModel) order_tbl_qty.getModel();
         table.setRowCount(0);
         ResultSet record =  con.executeQuery("SELECT * \n" +
                                               "FROM order_details\n" +
                                               "INNER JOIN ordered_product ON ordered_product.order_id = order_details.order_id\n" +
                                               "INNER JOIN products ON products.product_id = ordered_product.product_id\n" +
                                               "WHERE order_details.order_id='"+order_tbl_orders.getValueAt(order_tbl_orders.getSelectedRow(), 0)+"'");
            while(record.next()){
            order_lbl_cusId.setText(record.getString("order_details.cus_id"));
            order_lbl_cusName.setText(record.getString("order_details.order_cus_name"));
            order_lbl_address.setText(record.getString("order_details.order_cus_address"));
            order_lbl_phoneNo.setText(record.getString("order_details.order_cus_phone"));
            order_lbl_DilDate.setText(record.getString("order_details.order_delivery_date"));
            order_lbl_DilTime.setText(record.getString("order_details.order_delivery_time"));
            order_lbl_msg.setText(record.getString("order_details.order_other_messages"));           
            order_lbl_anytime.setText(record.getString("order_details.delivery_anytime"));
                    
            //update ordered_products table(qty)
                 
                Vector rc = new Vector();
                rc.add(record.getString("ordered_product.product_id"));
                rc.add(record.getString("products.product_name"));
                rc.add(record.getString("ordered_product.quantity"));
                table.addRow(rc);
           
             if("Delivered".equals(record.getString("order_details.order_status"))){
                notify_delvrd.setVisible(true); 
                notify_notDel.setVisible(false);
                notify_cancelled.setVisible(false);
            }else if("Cancelled".equals(record.getString("order_details.order_status"))){
                notify_cancelled.setVisible(true);
                notify_notDel.setVisible(false);
                notify_delvrd.setVisible(false);
            }else{
                notify_cancelled.setVisible(false);
                notify_notDel.setVisible(true);
                notify_delvrd.setVisible(false);
            
            }  
           
            }
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_order_tbl_ordersMouseClicked

    private void order_btn_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btn_deliveryActionPerformed
      try{
         Statement con = dbConnection.db().createStatement();
         con.executeUpdate("UPDATE order_details set order_status='Delivered' WHERE order_id='"+order_tbl_orders.getValueAt(order_tbl_orders.getSelectedRow(),0)+"' " );
          JOptionPane.showMessageDialog(null, "Order Saved as Delivered");
         }catch (Exception ex) {
            
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        notify_delvrd.setVisible(true);
        notify_notDel.setVisible(false);
        notify_cancelled.setVisible(false);
                                            
    }//GEN-LAST:event_order_btn_deliveryActionPerformed

    private void order_btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btn_cancelActionPerformed
         try{
         Statement con = dbConnection.db().createStatement();
         con.executeUpdate("UPDATE order_details set order_status='Cancelled' WHERE order_id='"+order_tbl_orders.getValueAt(order_tbl_orders.getSelectedRow(),0)+"' " );
         JOptionPane.showMessageDialog(null, "Order Saved as Cancelled");
         }catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        notify_cancelled.setVisible(true);
        notify_delvrd.setVisible(false);
        notify_notDel.setVisible(false);
        
    }//GEN-LAST:event_order_btn_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       customerDetails stw= new customerDetails();
       stw.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    public void OrdersTableUpdate() {
        DefaultTableModel table = (DefaultTableModel) order_tbl_orders.getModel();
        table.setRowCount(0);
        
        try {
            Statement con = dbConnection.db().createStatement();
            java.sql.ResultSet record =  con.executeQuery("SELECT * FROM order_details ORDER BY order_id DESC " );
            while(record.next()){
                Vector rc = new Vector();
                rc.add(record.getString("order_id"));
                rc.add(record.getString("order_dateTime"));
                
               
                table.addRow(rc);
            }
        } catch (Exception ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel notify_cancelled;
    private javax.swing.JLabel notify_delvrd;
    private javax.swing.JLabel notify_notDel;
    private javax.swing.JButton order_btn_cancel;
    private javax.swing.JButton order_btn_delivery;
    private javax.swing.JLabel order_lbl_DilDate;
    private javax.swing.JLabel order_lbl_DilTime;
    private javax.swing.JTextField order_lbl_address;
    private javax.swing.JLabel order_lbl_anytime;
    private javax.swing.JLabel order_lbl_cusId;
    private javax.swing.JLabel order_lbl_cusName;
    private javax.swing.JTextField order_lbl_msg;
    private javax.swing.JLabel order_lbl_phoneNo;
    private javax.swing.JTable order_tbl_orders;
    private javax.swing.JTable order_tbl_qty;
    // End of variables declaration//GEN-END:variables
}
