/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dhanuka
 */
public class print_label extends javax.swing.JFrame {

    /**
     * Creates new form print_label
     */
    public print_label() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prntLBL_txt_lbl = new javax.swing.JTextField();
        prntLBL_txt_bcode = new javax.swing.JTextField();
        prntLBL_btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchase_bill = new javax.swing.JTextPane();

        setTitle("Print Barcode Label");
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Barcode");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 71, 50, 20);

        jLabel2.setText("Number of Labels");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 135, 100, 30);

        prntLBL_txt_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prntLBL_txt_lblKeyTyped(evt);
            }
        });
        getContentPane().add(prntLBL_txt_lbl);
        prntLBL_txt_lbl.setBounds(210, 140, 50, 30);

        prntLBL_txt_bcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prntLBL_txt_bcodeKeyTyped(evt);
            }
        });
        getContentPane().add(prntLBL_txt_bcode);
        prntLBL_txt_bcode.setBounds(210, 70, 50, 30);

        prntLBL_btn_print.setText("Print");
        prntLBL_btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prntLBL_btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(prntLBL_btn_print);
        prntLBL_btn_print.setBounds(130, 220, 90, 30);

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportView(purchase_bill);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 230, 6, 0);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prntLBL_btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prntLBL_btn_printActionPerformed
      purchase_bill();
    }//GEN-LAST:event_prntLBL_btn_printActionPerformed

    private void prntLBL_txt_bcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prntLBL_txt_bcodeKeyTyped
        if (!(Character.isLetter(evt.getKeyChar()))) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_prntLBL_txt_bcodeKeyTyped

    private void prntLBL_txt_lblKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prntLBL_txt_lblKeyTyped
        if (!(Character.isLetter(evt.getKeyChar()))) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_prntLBL_txt_lblKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print_label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print_label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print_label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print_label.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print_label().setVisible(true);
            }
        });
    }

      public void purchase_bill(){
      
      
       int nmber = Integer.parseInt(prntLBL_txt_lbl.getText());
       
        String table="";
        for (int x = 0; x < nmber ; x++) {   
              table += "<table border=\"1\" width=\"200\" height=\"200\" align=\"center\">\n" ;            
              table += "<tr align=\"center\">\n";
              table +=  "\n";
              table +=   "<td  height=\"100\"><p><h5>Rajaguru Stores</h5> <h5> Barcode</h5><h3> "  +prntLBL_txt_bcode.getText()+ "</h3></p></td></tr></table></br> ";
              
              
             
             
             
             
     }   
          System.out.println(table);
        
         purchase_bill.setContentType("text/html");
        purchase_bill.setText("<html><body>\n" +

     table+                  

"</body>\n" +
"</html>");
        try {
            purchase_bill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prntLBL_btn_print;
    private javax.swing.JTextField prntLBL_txt_bcode;
    private javax.swing.JTextField prntLBL_txt_lbl;
    private javax.swing.JTextPane purchase_bill;
    // End of variables declaration//GEN-END:variables
}
