/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.dbConnection;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka
 */
public class stockReport extends javax.swing.JFrame {

    /**
     * Creates new form stockReport
     */
    public stockReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total_qty_eql = new javax.swing.JRadioButton();
        total_qty_larger = new javax.swing.JRadioButton();
        total_qty_less = new javax.swing.JRadioButton();
        total_qty = new javax.swing.JTextField();
        pro_id = new javax.swing.JTextField();

        setTitle("Stock Report");
        setBackground(new java.awt.Color(255, 255, 204));
        setMaximumSize(new java.awt.Dimension(200, 200));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Genarate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 240, 80, 30);

        jLabel1.setText("Total Qty:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 130, 70, 14);

        jLabel2.setText("Product ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 70, 14);

        buttonGroup1.add(total_qty_eql);
        total_qty_eql.setText("=");
        getContentPane().add(total_qty_eql);
        total_qty_eql.setBounds(130, 130, 33, 23);

        buttonGroup1.add(total_qty_larger);
        total_qty_larger.setText(">");
        getContentPane().add(total_qty_larger);
        total_qty_larger.setBounds(130, 160, 33, 23);

        buttonGroup1.add(total_qty_less);
        total_qty_less.setText("<");
        total_qty_less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_qty_lessActionPerformed(evt);
            }
        });
        getContentPane().add(total_qty_less);
        total_qty_less.setBounds(130, 190, 40, 23);
        getContentPane().add(total_qty);
        total_qty.setBounds(180, 130, 70, 30);

        pro_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pro_idFocusGained(evt);
            }
        });
        pro_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pro_idKeyTyped(evt);
            }
        });
        getContentPane().add(pro_id);
        pro_id.setBounds(180, 40, 70, 30);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void total_qty_lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_qty_lessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_qty_lessActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        String sql_cmd="";
        if(pro_id.getText().equals("") && total_qty.getText().equals("")){
        
            sql_cmd="SELECT stock. * , products.product_name\n" +
                    "FROM stock\n" +
                    "INNER JOIN products ON products.product_id = stock.product_id\n";
                   
        
        }else  if(!pro_id.getText().equals("") && total_qty.getText().equals("")){
        
            sql_cmd="SELECT stock. * , products.product_name\n" +
                    "FROM stock\n" +
                    "INNER JOIN products ON products.product_id = stock.product_id\n"+
                    "WHERE stock.product_id ='"+pro_id.getText()+"' ";

        }else  if(!pro_id.getText().equals("") && !total_qty.getText().equals("")){
            
            if(total_qty_eql.isSelected()){
               sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "WHERE stock.product_id ='"+pro_id.getText()+"' \n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) ='"+total_qty.getText()+"'"; 
            }else if(total_qty_larger.isSelected()){
                sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "WHERE stock.product_id ='"+pro_id.getText()+"' \n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) >'"+total_qty.getText()+"'";
            }else if(total_qty_less.isSelected()){
                sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "WHERE stock.product_id ='"+pro_id.getText()+"' \n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) <'"+total_qty.getText()+"'";
            }
                
        }else  if(pro_id.getText().equals("") && !total_qty.getText().equals("")){
        
            if(total_qty_eql.isSelected()){
               sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) ='"+total_qty.getText()+"'"; 
            }else  if(total_qty_larger.isSelected()){
                 sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) >'"+total_qty.getText()+"'";  
             }else  if(total_qty_less.isSelected()){
                 sql_cmd="SELECT stock. * , products.product_name\n" +
                       "FROM stock\n" +
                       "INNER JOIN products ON products.product_id = stock.product_id\n" +
                       "GROUP BY product_id\n" +
                       "HAVING SUM( stock.qauntity ) <'"+total_qty.getText()+"'";  
             }
        }
        
        Document doc = new Document();
        
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                            Date date = new Date();
                            String report_date = dateFormat.format(date);
                            
                            
                            
        try{
        PdfWriter.getInstance(doc, new FileOutputStream("report_stock.pdf"));
        doc.open();
       
        Statement con = dbConnection.db().createStatement();
        ResultSet record =  con.executeQuery(sql_cmd);
        
        //ResultSet record2 =  con.executeQuery("SELECT COUNT(*) AS total FROM supplied_products ");
        
        
        
        Paragraph H1 = new Paragraph("Rajaguru Stores" , FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD,BaseColor.BLUE));
            H1.setAlignment(Element.ALIGN_CENTER);
            H1.setSpacingAfter(20);
        doc.add(H1);
        
        
        Paragraph H2 = new Paragraph("Current Stock Details" , FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
        doc.add(H2);
        
        Paragraph H3 = new Paragraph("Date Created : "+report_date+"" , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        doc.add(H3);
        
        Paragraph H4 = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------");
        H4.setSpacingAfter(20);
        doc.add(H4);
        
       /* Paragraph H6 = new Paragraph(showRcrdMsg , FontFactory.getFont(FontFactory.TIMES_BOLD,10));
        H6.setSpacingAfter(20);
        doc.add(H6);
        */
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(95);
        
        PdfPCell cell1 = new    PdfPCell(new Paragraph("Barcode"));
        cell1.setBackgroundColor(BaseColor.GRAY);
       
        
        PdfPCell cell2 = new    PdfPCell(new Paragraph("Product ID"));
        cell2.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell3 = new    PdfPCell(new Paragraph("Product Name"));
        cell3.setBackgroundColor(BaseColor.GRAY);
        
        PdfPCell cell4 = new    PdfPCell(new Paragraph("Quantity"));
        cell4.setBackgroundColor(BaseColor.GRAY);
        
       
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cell4);
          
        
        
            while(record.next()){
            table.addCell(""+record.getString("stock.bar_code")+"");
            table.addCell(""+record.getString("stock.product_id")+"");
            table.addCell(""+record.getString("products.product_name")+"");
            table.addCell(""+record.getString("stock.qauntity")+"");
                    }           
         doc.add(table);   
         
        //Paragraph H5 = new Paragraph("Total Records : "+record2.getString("total")+"");
        //doc.add(H5); 
         
        doc.close();
        openReportStock();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"There is something wrong of inputs Or \nClose the currently open PDF report and Try Again....! ");
           Logger.getLogger(grnWindow.class.getName()).log(Level.SEVERE, null, ex);

        } 
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

     public void openReportStock(){
        
        try {
            Desktop.getDesktop().open(new File("report_stock.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void pro_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_idKeyTyped
        
    }//GEN-LAST:event_pro_idKeyTyped

    private void pro_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pro_idFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_idFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField pro_id;
    private javax.swing.JTextField total_qty;
    private javax.swing.JRadioButton total_qty_eql;
    private javax.swing.JRadioButton total_qty_larger;
    private javax.swing.JRadioButton total_qty_less;
    // End of variables declaration//GEN-END:variables
}
